# baseURL = 'https://corinnabath.de'
baseURL = 'https://corinnabath.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "minimal-theme"
sectionPagesMenu = "main"
[params]
  githubRepo = "https://github.com/corinnabath/corinnabath.github.io"
  githubEditPath = "edit/main/"
